version: "3"
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  nacos:
    # mysql 启动好以后要重新移动一次
    image: nacos/nacos-server:v2.0.4
    container_name: nacos
    env_file:
      - ./nacos/conf/nacos.env
    environment:
      JVM_XMS: 256m
      JVM_XMX: 256m
    links:
      - mysql:mysql
    volumes:
      - ./nacos/conf/nacos.properties:/home/nacos/init.d/custom.properties
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  es-master:
    container_name: es-master
    hostname: es-master
    image: docker.elastic.co/elasticsearch/elasticsearch:${elasticsearch_version}
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/master/data:/usr/share/elasticsearch/data
      - ./elasticsearch/master/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/master/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./elasticsearch/master/plugins:/usr/share/elasticsearch/plugins
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    depends_on:
#      - nacos
#    restart: on-failure
#  grafana:
#    container_name: grafana
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    restart: on-failure
  kibana:
    container_name: kibana
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:${elasticsearch_version}
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - elasticsearch.hosts=http://es-master:9200
    depends_on:
      - es-master
#  logstash:
#    container_name: logstash
#    hostname: logstash
#    image: docker.elastic.co/logstash/logstash:${elasticsearch_version}
#    restart: always
#    volumes:
#      # 映射到容器中
#      - ./logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    environment:
#      TZ: Asia/Shanghai
#      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
#    links:
#      - es-master:es-master
#    ports:
#      - "4560:4560"
#    depends_on:
#      - es-master
  seata-server:
    image: seataio/seata-server
    hostname: seata-server
    container_name: seata-server
    privileged: true
    restart: always
    environment:
      # spring-cloud 无法访问容器中的 ip,配置外网映射地址
      SEATA_IP: 1.15.19.68
    ports:
      - 8091:8091
    volumes:
      - ./application.yml:/seata-server/resources/application.yml
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes", "--requirepass","158262751" ]
