version: "3"
services:
  seata-server:
    image: seataio/seata-server
    hostname: seata-server
    container_name: seata-server
    privileged: true
    environment:
      SEATA_CONFIG_NAME: file:/root/seata-config/registry
    ports:
      - "8091:8091"
    volumes:
      - ./config:/root/seata-config