version: '3.5'
services:
  rmqnamesrv-a:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv-a
    hostname: rmqnamesrv-a
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/logs/nameserver-a:/opt/logs
      - ./rocketmq/store/nameserver-a:/opt/store
    command: sh mqnamesrv
#    networks:
#      rmq:
#        aliases:
#          - rmqnamesrv-a
  rmqnamesrv-b:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv-b
    hostname: rmqnamesrv-b
    ports:
      - 9877:9877
    volumes:
      - ./rocketmq/logs/nameserver-b:/opt/logs
      - ./rocketmq/store/nameserver-b:/opt/store
    command: sh mqnamesrv
#    networks:
#      rmq:
#        aliases:
#          - rmqnamesrv-b

  rmqbroker-a:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker-a
    hostname: rmqbroker-a
    ports:
      - 10911:10911
    volumes:
      - ./rocketmq/logs/broker-a:/opt/logs
      - ./rocketmq/store/broker-a:/opt/store
      - ./broker-a.conf:/opt/rocketmq/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
#    networks:
#      rmq:
#        aliases:
#          - rmqbroker-a

  rmqbroker-b:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker-b
    hostname: rmqbroker-b
    ports:
      - 10909:10909
    volumes:
      - ./rocketmq/logs/broker-b:/opt/logs
      - ./rocketmq/store/broker-b:/opt/store
      - ./broker-b.conf:/opt/rocketmq/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-b:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
#    networks:
#      rmq:
#        aliases:
#          - rmqbroker-b
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    hostname: rmqconsole
    ports:
      - 9001:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=rmqnamesrv-a:9876;rmqnamesrv-b:9877 -Dcom.rocketmq.sendMessageWithVIPChannel=false
#    networks:
#      rmq:
#        aliases:
#          - rmqconsole
#networks:
#  rmq:
#    name: rmq
#    driver: bridge
