version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
  registry.yapi:
    image: registry.cn-hangzhou.aliyuncs.com/anoy/yapi
    container_name: yapi
    working_dir: /api/vendors
    command: server/app.js
    links:
      - mongo:mongo
