version: '3.5'
services:
  rmqnamesrv-a:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv-a
    hostname: rmqnamesrv-a
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/logs/nameserver-a:/opt/logs
      - ./rocketmq/store/nameserver-a:/opt/store
    command: sh mqnamesrv
#    networks:
#      rmq:
#        aliases:
#          - rmqnamesrv-a
  rmqnamesrv-b:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv-b
    hostname: rmqnamesrv-b
    ports:
      - 9877:9877
    volumes:
      - ./rocketmq/logs/nameserver-b:/opt/logs
      - ./rocketmq/store/nameserver-b:/opt/store
    command: sh mqnamesrv
#    networks:
#      rmq:
#        aliases:
#          - rmqnamesrv-b

  rmqbroker-a:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker-a
    hostname: rmqbroker-a
    ports:
      - 10911:10911
    volumes:
      - ./rocketmq/logs/broker-a:/opt/logs
      - ./rocketmq/store/broker-a:/opt/store
      - ./broker-a.conf:/opt/rocketmq/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-Xms512M -Xmx512M -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
#    networks:
#      rmq:
#        aliases:
#          - rmqbroker-a
  rmqbroker-a-s:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker-a-s
    hostname: rmqbroker-a-s
    ports:
      - 10912:10911
    volumes:
      - ./rocketmq/logs/broker-a-s:/opt/logs
      - ./rocketmq/store/broker-a-s:/opt/store
      - ./broker-a-s.conf:/opt/rocketmq/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-Xms512M -Xmx512M -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b

  rmqbroker-b:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker-b
    hostname: rmqbroker-b
    ports:
      - 10909:10909
    volumes:
      - ./rocketmq/logs/broker-b:/opt/logs
      - ./rocketmq/store/broker-b:/opt/store
      - ./broker-b.conf:/opt/rocketmq/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-b:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-Xms512M -Xmx512M -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
#    networks:
#      rmq:
#        aliases:
#          - rmqbroker-b
  rmqbroker-b-s:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker-b-s
    hostname: rmqbroker-b-s
    ports:
      - 10910:10909
    volumes:
      - ./rocketmq/logs/broker-b-s:/opt/logs
      - ./rocketmq/store/broker-b-s:/opt/store
      - ./broker-b-s.conf:/opt/rocketmq/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-b:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-Xms512M -Xmx512M -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
  rmqconsole:
    image: pangliang/rocketmq-console-ng
    container_name: rmqconsole
    hostname: rmqconsole
    ports:
      - 9001:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=rmqnamesrv-a:9876;rmqnamesrv-b:9877 -Dcom.rocketmq.sendMessageWithVIPChannel=false
#    networks:
#      rmq:
#        aliases:
#          - rmqconsole
#networks:
#  rmq:
#    name: rmq
#    driver: bridge
