mkdir -p ./rocketmq/logs/nameserver-a
mkdir -p ./rocketmq/logs/nameserver-b
mkdir -p ./rocketmq/logs/nameserver-c
mkdir -p ./rocketmq/store/nameserver-a
mkdir -p ./rocketmq/store/nameserver-b
mkdir -p ./rocketmq/store/nameserver-c
mkdir -p ./rocketmq/logs/broker-a
mkdir -p ./rocketmq/logs/broker-a-s
mkdir -p ./rocketmq/logs/broker-b
mkdir -p ./rocketmq/logs/broker-b-s
mkdir -p ./rocketmq/store/broker-a
mkdir -p ./rocketmq/store/broker-a-s
mkdir -p ./rocketmq/store/broker-b
mkdir -p ./rocketmq/store/broker-b-s
