version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    volumes:
      # mysql的数据文件
      - ./mysql/data:/var/lib/mysql
      # mysql配置文件
#      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server
    volumes:
      # 需要添加mysql8的插件
#      - ./nacos/plugins/mysql/:/home/nacos/plugins/mysql/
      # 把日志文件映射出来
      - ./nacos/cluster-logs/nacos1:/home/nacos/logs
      # 把配置文件映射出来
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      # 集群配置文件
      - ./nacos/env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server
    container_name: nacos2
    volumes:
#      - ./nacos/plugins/mysql/:/home/nacos/plugins/mysql/
      - ./nacos/cluster-logs/nacos2:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
    env_file:
      - ./nacos/env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server
    container_name: nacos3
    volumes:
#      - ./nacos/plugins/mysql/:/home/nacos/plugins/mysql/
      - ./nacos/cluster-logs/nacos3:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8850:8848"
    env_file:
      - ./nacos/env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
  seata-server1:
    image: seataio/seata-server
    hostname: seata-server1
    container_name: seata-server1
    privileged: true
    restart: always
    ports:
      - 8091:8091
    environment:
      # spring-cloud 无法访问容器中的 ip,配置外网映射地址
      SEATA_IP: 192.168.1.10
      SEATA_PORT: 8091
    volumes:
      - ./seata/conf/application.yml:/seata-server/resources/application.yml
    links:
      - nacos1
      - nacos2
      - nacos3
      - mysql
    depends_on:
      - mysql
      - nacos1
      - nacos2
      - nacos3
  seata-server2:
    image: seataio/seata-server
    hostname: seata-server2
    container_name: seata-server2
    privileged: true
    restart: always
    ports:
      - 8092:8092
    environment:
      # spring-cloud 无法访问容器中的 ip,配置外网映射地址
      SEATA_IP: 192.168.1.10
      SEATA_PORT: 8092
    volumes:
      - ./seata/conf/application.yml:/seata-server/resources/application.yml
    links:
      - nacos1
      - nacos2
      - nacos3
      - mysql
    depends_on:
      - mysql
      - nacos1
      - nacos2
      - nacos3
  seata-server3:
    image: seataio/seata-server
    hostname: seata-server3
    container_name: seata-server3
    privileged: true
    restart: always
    environment:
      # spring-cloud 无法访问容器中的 ip,配置外网映射地址
      SEATA_IP: 192.168.1.10
      SEATA_PORT: 8093
    ports:
      - 8093:8093
    volumes:
      - ./seata/conf/application.yml:/seata-server/resources/application.yml
    links:
      - nacos1
      - nacos2
      - nacos3
      - mysql
    depends_on:
      - mysql
      - nacos1
      - nacos2
      - nacos3