version: "3.3"

services:

  mysql-master0: &mysql-master0
    image: amd64/mysql
#    image: amd64/mysql:${TAG}
    container_name: mysql-iflow-master0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MASTER_MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - "36005:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql-master0-data:/var/lib/mysql
#      - ./init-db-sql/iflow.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init-db-sql/init-master.sh:/docker-entrypoint-initdb.d/2-init-master.sh
    command: [
        "--default-authentication-plugin=mysql_native_password",
        "--log-bin=mysql-bin",
        "--server-id=${MASTER0_SERVER_ID}",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--innodb_flush_log_at_trx_commit=1",
        "--sync_binlog=1"
    ]
  mysql-master0-node1: &mysql-master0-node1
    <<: *mysql-master0
    container_name: mysql-iflow-master0-node1
    environment:
      - MYSQL_ROOT_PASSWORD=${NODE_MYSQL_ROOT_PASSWORD}
      - MASTER_MYSQL_ROOT_PASSWORD=${MASTER_MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - "36006:3306"
    depends_on:
      - mysql-master0
    volumes:
      - ./mysql-master0-node-1-data:/var/lib/mysql
#      - ./init-db-sql/iflow.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init-db-sql/init-master0-node.sh:/docker-entrypoint-initdb.d/2-init-node.sh
    command: [
        "--default-authentication-plugin=mysql_native_password",
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=${MASTER0_NODE_1_SERVER_ID}",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
    ]

  mysql-master0-node2:
    <<: *mysql-master0-node1
    container_name: mysql-iflow-master0-node2
    environment:
      - MYSQL_ROOT_PASSWORD=${NODE_MYSQL_ROOT_PASSWORD}
      - MASTER_MYSQL_ROOT_PASSWORD=${MASTER_MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - "36007:3306"
    volumes:
      - ./mysql-master0-node-2-data:/var/lib/mysql
#      - ./init-db-sql/iflow.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init-db-sql/init-master0-node.sh:/docker-entrypoint-initdb.d/2-init-node.sh
    command: [
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=${MASTER0_NODE_2_SERVER_ID}",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
    ]
  mysql-master1: &mysql-master1
#    image: amd64/mysql:${TAG}
    image: amd64/mysql
    container_name: mysql-iflow-master1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MASTER_MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - "36008:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql-master1-data:/var/lib/mysql
#      - ./init-db-sql/iflow.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init-db-sql/init-master.sh:/docker-entrypoint-initdb.d/2-init-master.sh
    command: [
        "--default-authentication-plugin=mysql_native_password",
        "--log-bin=mysql-bin",
        "--server-id=${MASTER1_SERVER_ID}",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--innodb_flush_log_at_trx_commit=1",
        "--sync_binlog=1"
    ]
  mysql-master1-node1:
    <<: *mysql-master1
    container_name: mysql-iflow-master1-node1
    environment:
      - MYSQL_ROOT_PASSWORD=${NODE_MYSQL_ROOT_PASSWORD}
      - MASTER_MYSQL_ROOT_PASSWORD=${MASTER_MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - "36009:3306"
    depends_on:
      - mysql-master1
    volumes:
      - ./mysql-master1-node-1-data:/var/lib/mysql
#      - ./init-db-sql/iflow.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init-db-sql/init-master1-node.sh:/docker-entrypoint-initdb.d/2-init-node.sh
    command: [
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=${MASTER1_NODE_1_SERVER_ID}",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
    ]



