apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.33.1
imageRepository: registry.k8s.io
controlPlaneEndpoint: "master:6443"  # 修改为你的主节点IP
networking:
  podSubnet: "10.244.0.0/16"  # 建议与你的 CNI 插件匹配，例如 Flannel


---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "iptables"
